import type { AppFlowSpec } from "./types";

export const defaultSpec: AppFlowSpec = {
    id: "chauchita-v1",
    name: "Chauchita",
    version: "1.0.0",
    description: "Plataforma para conectar trabajadores independientes con clientes",
    mockData: {
        workers: [
            {
                id: "w1",
                name: "Carlos Mendoza",
                category: "Plomero",
                city: "Quito",
                rating: 4.8,
                description: "Instalaciones y reparaciones de tuberías.",
            },
            {
                id: "w2",
                name: "Andrea Ruiz",
                category: "Pintora",
                city: "Quito",
                rating: 4.7,
                description: "Pintura interior y exterior.",
            },
            {
                id: "w3",
                name: "Luis Cedeño",
                category: "Electricista",
                city: "Guayaquil",
                rating: 4.5,
                description: "Instalaciones eléctricas residenciales.",
            },
            {
                id: "w4",
                name: "María Torres",
                category: "Limpieza",
                city: "Cuenca",
                rating: 4.9,
                description: "Limpieza profunda para casas y oficinas.",
            },
        ],
        cities: [
            { id: "quito", name: "Quito" },
            { id: "guayaquil", name: "Guayaquil" },
            { id: "cuenca", name: "Cuenca" },
        ],
    },
    businessRules: [
        {
            id: "WORKERS_FILTER_001",
            title: "Filtro por ciudad",
            description: "Si el usuario selecciona una ciudad, la lista de trabajadores se filtra por ciudad.",
            relatedScreens: ["workers_list"],
            relatedComponents: ["city_selector", "workers_grid"],
        },
        {
            id: "WORKERS_SEARCH_001",
            title: "Búsqueda de trabajadores",
            description: "La búsqueda filtra por nombre, categoría y descripción.",
            relatedScreens: ["workers_list"],
            relatedComponents: ["search_input"],
        },
        {
            id: "WORKERS_EMPTY_001",
            title: "Estado vacío",
            description: "Si no hay resultados, se muestra un estado vacío.",
            relatedScreens: ["workers_list"],
        },
        {
            id: "JOB_PUBLISH_001",
            title: "Publicar trabajo",
            description: "Para publicar un trabajo se requiere título, descripción, categoría y ciudad.",
            relatedScreens: ["publish_job"],
        },
    ],
    changeLog: [
        {
            version: "1.0.0",
            summary: "Versión inicial con flujo completo de trabajadores",
            createdAt: "2026-05-11",
        },
    ],
    screens: [
        {
            id: "home",
            name: "Home",
            type: "screen",
            description: "Pantalla de inicio",
            nodePosition: { x: 100, y: 100 },
            canvas: {
                device: "mobile",
                columns: 12,
                rows: 20,
                rowHeight: 40,
            },
            components: [
                {
                    id: "home_title",
                    type: "text",
                    label: "Bienvenido a Chauchita",
                    layout: { colStart: 1, colSpan: 12, rowStart: 5, rowSpan: 2 },
                },
                {
                    id: "home_button",
                    type: "button",
                    label: "Comenzar",
                    layout: { colStart: 3, colSpan: 8, rowStart: 10, rowSpan: 1 },
                    action: {
                        type: "navigate",
                        target: "onboarding",
                    },
                },
            ],
        },
        {
            id: "onboarding",
            name: "Onboarding",
            type: "screen",
            description: "Introducción a la app",
            nodePosition: { x: 400, y: 100 },
            canvas: {
                device: "mobile",
                columns: 12,
                rows: 20,
                rowHeight: 40,
            },
            components: [
                {
                    id: "onboarding_title",
                    type: "text",
                    label: "Encuentra trabajadores calificados",
                    layout: { colStart: 1, colSpan: 12, rowStart: 5, rowSpan: 2 },
                },
                {
                    id: "onboarding_button",
                    type: "button",
                    label: "Explorar trabajadores",
                    layout: { colStart: 3, colSpan: 8, rowStart: 12, rowSpan: 1 },
                    action: {
                        type: "navigate",
                        target: "workers_list",
                    },
                },
            ],
        },
        {
            id: "workers_list",
            name: "Lista de trabajadores",
            type: "screen",
            description: "Pantalla principal con lista de trabajadores disponibles",
            nodePosition: { x: 700, y: 100 },
            canvas: {
                device: "mobile",
                columns: 12,
                rows: 25,
                rowHeight: 40,
            },
            components: [
                {
                    id: "workers_title",
                    type: "text",
                    label: "Trabajadores",
                    layout: { colStart: 1, colSpan: 12, rowStart: 1, rowSpan: 1 },
                    props: { fontSize: "xl", fontWeight: "bold" },
                },
                {
                    id: "city_selector",
                    type: "select",
                    label: "Ciudad: Quito",
                    layout: { colStart: 1, colSpan: 12, rowStart: 2, rowSpan: 1 },
                    action: {
                        type: "open_modal",
                        target: "city_modal",
                    },
                },
                {
                    id: "search_input",
                    type: "input",
                    placeholder: "Buscar trabajador",
                    layout: { colStart: 1, colSpan: 10, rowStart: 3, rowSpan: 1 },
                    action: {
                        type: "filter_data",
                        params: { dataSource: "workers" },
                    },
                },
                {
                    id: "filter_button",
                    type: "icon_button",
                    icon: "filter",
                    layout: { colStart: 11, colSpan: 2, rowStart: 3, rowSpan: 1 },
                    action: {
                        type: "open_modal",
                        target: "filters_modal",
                    },
                },
                {
                    id: "workers_grid",
                    type: "grid",
                    dataSource: "workers",
                    fields: ["name", "category", "city", "rating"],
                    layout: { colStart: 1, colSpan: 12, rowStart: 4, rowSpan: 18 },
                    props: { columns: 2 },
                    action: {
                        type: "navigate",
                        target: "worker_profile",
                    },
                },
                {
                    id: "bottom_nav",
                    type: "bottom_nav",
                    layout: { colStart: 1, colSpan: 12, rowStart: 23, rowSpan: 2 },
                },
            ],
        },
        {
            id: "city_modal",
            name: "Selector de ciudad",
            type: "modal",
            description: "Modal para seleccionar ciudad",
            nodePosition: { x: 700, y: 400 },
            canvas: {
                device: "mobile",
                columns: 12,
                rows: 15,
                rowHeight: 40,
            },
            components: [
                {
                    id: "city_modal_title",
                    type: "text",
                    label: "Selecciona tu ciudad",
                    layout: { colStart: 1, colSpan: 12, rowStart: 1, rowSpan: 1 },
                },
                {
                    id: "city_list",
                    type: "list",
                    dataSource: "cities",
                    fields: ["name"],
                    layout: { colStart: 1, colSpan: 12, rowStart: 2, rowSpan: 10 },
                    action: {
                        type: "close_modal",
                    },
                },
            ],
        },
        {
            id: "worker_profile",
            name: "Perfil del trabajador",
            type: "screen",
            description: "Detalle de un trabajador específico",
            nodePosition: { x: 1000, y: 100 },
            canvas: {
                device: "mobile",
                columns: 12,
                rows: 25,
                rowHeight: 40,
            },
            components: [
                {
                    id: "worker_image",
                    type: "image_placeholder",
                    layout: { colStart: 1, colSpan: 12, rowStart: 1, rowSpan: 4 },
                },
                {
                    id: "worker_name",
                    type: "text",
                    label: "Carlos Mendoza",
                    layout: { colStart: 1, colSpan: 12, rowStart: 5, rowSpan: 1 },
                    props: { fontSize: "xl", fontWeight: "bold" },
                },
                {
                    id: "worker_category",
                    type: "text",
                    label: "Plomero",
                    layout: { colStart: 1, colSpan: 12, rowStart: 6, rowSpan: 1 },
                },
                {
                    id: "worker_description",
                    type: "text",
                    label: "Instalaciones y reparaciones de tuberías.",
                    layout: { colStart: 1, colSpan: 12, rowStart: 7, rowSpan: 2 },
                },
                {
                    id: "contact_button",
                    type: "button",
                    label: "Contactar",
                    layout: { colStart: 2, colSpan: 10, rowStart: 15, rowSpan: 1 },
                },
            ],
        },
        {
            id: "publish_job",
            name: "Publicar trabajo",
            type: "form",
            description: "Formulario para publicar un nuevo trabajo",
            nodePosition: { x: 1000, y: 400 },
            canvas: {
                device: "mobile",
                columns: 12,
                rows: 25,
                rowHeight: 40,
            },
            components: [
                {
                    id: "publish_title",
                    type: "text",
                    label: "Publicar trabajo",
                    layout: { colStart: 1, colSpan: 12, rowStart: 1, rowSpan: 1 },
                    props: { fontSize: "xl", fontWeight: "bold" },
                },
                {
                    id: "job_title_input",
                    type: "input",
                    placeholder: "Título del trabajo",
                    layout: { colStart: 1, colSpan: 12, rowStart: 3, rowSpan: 1 },
                },
                {
                    id: "job_description_input",
                    type: "textarea",
                    placeholder: "Descripción detallada",
                    layout: { colStart: 1, colSpan: 12, rowStart: 4, rowSpan: 3 },
                },
                {
                    id: "job_category_select",
                    type: "select",
                    label: "Categoría",
                    layout: { colStart: 1, colSpan: 12, rowStart: 7, rowSpan: 1 },
                },
                {
                    id: "job_city_select",
                    type: "select",
                    label: "Ciudad",
                    layout: { colStart: 1, colSpan: 12, rowStart: 8, rowSpan: 1 },
                },
                {
                    id: "publish_button",
                    type: "button",
                    label: "Publicar",
                    layout: { colStart: 2, colSpan: 10, rowStart: 15, rowSpan: 1 },
                    action: {
                        type: "submit_form",
                        target: "publish_success",
                    },
                },
            ],
        },
        {
            id: "publish_success",
            name: "Publicación exitosa",
            type: "screen",
            description: "Confirmación de publicación",
            nodePosition: { x: 1300, y: 400 },
            canvas: {
                device: "mobile",
                columns: 12,
                rows: 20,
                rowHeight: 40,
            },
            components: [
                {
                    id: "success_title",
                    type: "text",
                    label: "¡Trabajo publicado!",
                    layout: { colStart: 1, colSpan: 12, rowStart: 8, rowSpan: 2 },
                    props: { fontSize: "xl", fontWeight: "bold" },
                },
                {
                    id: "success_button",
                    type: "button",
                    label: "Volver a inicio",
                    layout: { colStart: 3, colSpan: 8, rowStart: 12, rowSpan: 1 },
                    action: {
                        type: "navigate",
                        target: "workers_list",
                    },
                },
            ],
        },
        {
            id: "profile_settings",
            name: "Configuración de perfil",
            type: "screen",
            description: "Ajustes del usuario",
            nodePosition: { x: 700, y: -200 },
            canvas: {
                device: "mobile",
                columns: 12,
                rows: 20,
                rowHeight: 40,
            },
            components: [
                {
                    id: "settings_title",
                    type: "text",
                    label: "Configuración",
                    layout: { colStart: 1, colSpan: 12, rowStart: 1, rowSpan: 1 },
                    props: { fontSize: "xl", fontWeight: "bold" },
                },
                {
                    id: "name_input",
                    type: "input",
                    placeholder: "Nombre",
                    layout: { colStart: 1, colSpan: 12, rowStart: 3, rowSpan: 1 },
                },
                {
                    id: "email_input",
                    type: "input",
                    placeholder: "Email",
                    layout: { colStart: 1, colSpan: 12, rowStart: 4, rowSpan: 1 },
                },
                {
                    id: "save_button",
                    type: "button",
                    label: "Guardar cambios",
                    layout: { colStart: 2, colSpan: 10, rowStart: 10, rowSpan: 1 },
                },
            ],
        },
    ],
    flows: [
        {
            id: "flow_1",
            sourceScreenId: "home",
            targetScreenId: "onboarding",
            label: "Comenzar",
            triggerComponentId: "home_button",
        },
        {
            id: "flow_2",
            sourceScreenId: "onboarding",
            targetScreenId: "workers_list",
            label: "Explorar",
            triggerComponentId: "onboarding_button",
        },
        {
            id: "flow_3",
            sourceScreenId: "workers_list",
            targetScreenId: "worker_profile",
            label: "Ver perfil",
            triggerComponentId: "workers_grid",
        },
        {
            id: "flow_4",
            sourceScreenId: "workers_list",
            targetScreenId: "city_modal",
            label: "Cambiar ciudad",
            triggerComponentId: "city_selector",
        },
        {
            id: "flow_5",
            sourceScreenId: "workers_list",
            targetScreenId: "publish_job",
            label: "Publicar trabajo",
        },
        {
            id: "flow_6",
            sourceScreenId: "publish_job",
            targetScreenId: "publish_success",
            label: "Publicar",
            triggerComponentId: "publish_button",
        },
        {
            id: "flow_7",
            sourceScreenId: "workers_list",
            targetScreenId: "profile_settings",
            label: "Configuración",
        },
    ],
};
